### ISSUE TITLE
[BUG] 1.8.8 NoSuchMethodError

### ISSUE THREAD

**Issue by gamerover98** [TozyMC/commands-api#5]
**Description**
The API doesn't work into a 1.8.8 Spigot server.
You can find the entire issue here: https://github.com/gamerover98/NoBlackSky/issues/3

**Log console**
```
[04:45:24] [Server thread/INFO]: [NoBlackSky] Enabling NoBlackSky v2.1
[04:45:24] [Server thread/ERROR]: Error occurred while enabling NoBlackSky v2.1 (Is it up to date?)
java.lang.NoSuchMethodError: com.google.common.base.Preconditions.checkState(ZLjava/lang/String;Ljava/lang/Object;)V
	at it.gamerover.nbs.libs.xyz.tozymc.spigot.api.command.CommandController.addCommand(CommandController.java:111) ~[?:?]
	at it.gamerover.nbs.command.PluginCommand.<init>(PluginCommand.java:30) ~[?:?]
	at it.gamerover.nbs.NoBlackSky.onEnable(NoBlackSky.java:108) ~[?:?]
	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:321) ~[1.8.8.jar:git-Spigot-db6de12-18fbb24]
	at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:340) [1.8.8.jar:git-Spigot-db6de12-18fbb24]
	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:405) [1.8.8.jar:git-Spigot-db6de12-18fbb24]
	at org.bukkit.craftbukkit.v1_8_R3.CraftServer.loadPlugin(CraftServer.java:357) [1.8.8.jar:git-Spigot-db6de12-18fbb24]
	at org.bukkit.craftbukkit.v1_8_R3.CraftServer.enablePlugins(CraftServer.java:317) [1.8.8.jar:git-Spigot-db6de12-18fbb24]
	at net.minecraft.server.v1_8_R3.MinecraftServer.s(MinecraftServer.java:414) [1.8.8.jar:git-Spigot-db6de12-18fbb24]
	at net.minecraft.server.v1_8_R3.MinecraftServer.k(MinecraftServer.java:378) [1.8.8.jar:git-Spigot-db6de12-18fbb24]
	at net.minecraft.server.v1_8_R3.MinecraftServer.a(MinecraftServer.java:333) [1.8.8.jar:git-Spigot-db6de12-18fbb24]
	at net.minecraft.server.v1_8_R3.DedicatedServer.init(DedicatedServer.java:263) [1.8.8.jar:git-Spigot-db6de12-18fbb24]
	at net.minecraft.server.v1_8_R3.MinecraftServer.run(MinecraftServer.java:525) [1.8.8.jar:git-Spigot-db6de12-18fbb24]
	at java.lang.Thread.run(Unknown Source) [?:1.8.0_201]
```

**Additional Information:**

- _Server Version_: CraftBukkit version git-Spigot-db6de12-18fbb24 (MC: 1.8.8) (Implementing API version 1.8.8-R0.1-SNAPSHOT)
- _Server Type_: Spigot

**Comment by gamerover98** [comment]
After the updating from 1.1 to 2.0 of your API, my plugin doesn't work with any spigot version but, it throws a different error message into the stack trace.

```
[05:23:57] [Server thread/INFO]: [NoBlackSky] Enabling NoBlackSky v2.1
[05:23:57] [Server thread/ERROR]: Error occurred while enabling NoBlackSky v2.1 (Is it up to date?)
java.lang.IllegalStateException: Command PluginCommand(name=NoBlackSky) is registered.
	at com.google.common.base.Preconditions.checkState(Preconditions.java:518) ~[PS-1.13.2.jar:git-Paper-655]
	at it.gamerover.nbs.libs.xyz.tozymc.spigot.api.command.CommandController.addCommand(CommandController.java:111) ~[?:?]
	at it.gamerover.nbs.command.PluginCommand.<init>(PluginCommand.java:30) ~[?:?]
	at it.gamerover.nbs.NoBlackSky.onEnable(NoBlackSky.java:108) ~[?:?]
	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:265) ~[PS-1.13.2.jar:git-Paper-655]
	at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:334) ~[PS-1.13.2.jar:git-Paper-655]
	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:412) ~[PS-1.13.2.jar:git-Paper-655]
	at org.bukkit.craftbukkit.v1_13_R2.CraftServer.enablePlugin(CraftServer.java:443) ~[PS-1.13.2.jar:git-Paper-655]
	at org.bukkit.craftbukkit.v1_13_R2.CraftServer.enablePlugins(CraftServer.java:357) ~[PS-1.13.2.jar:git-Paper-655]
	at net.minecraft.server.v1_13_R2.MinecraftServer.l(MinecraftServer.java:608) ~[PS-1.13.2.jar:git-Paper-655]
	at net.minecraft.server.v1_13_R2.MinecraftServer.a(MinecraftServer.java:570) ~[PS-1.13.2.jar:git-Paper-655]
	at net.minecraft.server.v1_13_R2.MinecraftServer.a(MinecraftServer.java:431) ~[PS-1.13.2.jar:git-Paper-655]
	at net.minecraft.server.v1_13_R2.DedicatedServer.init(DedicatedServer.java:316) ~[PS-1.13.2.jar:git-Paper-655]
	at net.minecraft.server.v1_13_R2.MinecraftServer.run(MinecraftServer.java:787) ~[PS-1.13.2.jar:git-Paper-655]
	at java.lang.Thread.run(Unknown Source) [?:1.8.0_201]
```

**Comment by TozyMC** [comment]
ok, i will check it soon

**Comment by TozyMC** [comment]
> After the updating from 1.1 to 2.0 of your API, my plugin doesn't work with any spigot version but, it throws a different error message into the stack trace.
> 
> ```
> [05:23:57] [Server thread/INFO]: [NoBlackSky] Enabling NoBlackSky v2.1
> [05:23:57] [Server thread/ERROR]: Error occurred while enabling NoBlackSky v2.1 (Is it up to date?)
> java.lang.IllegalStateException: Command PluginCommand(name=NoBlackSky) is registered.
> 	at com.google.common.base.Preconditions.checkState(Preconditions.java:518) ~[PS-1.13.2.jar:git-Paper-655]
> 	at it.gamerover.nbs.libs.xyz.tozymc.spigot.api.command.CommandController.addCommand(CommandController.java:111) ~[?:?]
> 	at it.gamerover.nbs.command.PluginCommand.<init>(PluginCommand.java:30) ~[?:?]
> 	at it.gamerover.nbs.NoBlackSky.onEnable(NoBlackSky.java:108) ~[?:?]
> 	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:265) ~[PS-1.13.2.jar:git-Paper-655]
> 	at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:334) ~[PS-1.13.2.jar:git-Paper-655]
> 	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:412) ~[PS-1.13.2.jar:git-Paper-655]
> 	at org.bukkit.craftbukkit.v1_13_R2.CraftServer.enablePlugin(CraftServer.java:443) ~[PS-1.13.2.jar:git-Paper-655]
> 	at org.bukkit.craftbukkit.v1_13_R2.CraftServer.enablePlugins(CraftServer.java:357) ~[PS-1.13.2.jar:git-Paper-655]
> 	at net.minecraft.server.v1_13_R2.MinecraftServer.l(MinecraftServer.java:608) ~[PS-1.13.2.jar:git-Paper-655]
> 	at net.minecraft.server.v1_13_R2.MinecraftServer.a(MinecraftServer.java:570) ~[PS-1.13.2.jar:git-Paper-655]
> 	at net.minecraft.server.v1_13_R2.MinecraftServer.a(MinecraftServer.java:431) ~[PS-1.13.2.jar:git-Paper-655]
> 	at net.minecraft.server.v1_13_R2.DedicatedServer.init(DedicatedServer.java:316) ~[PS-1.13.2.jar:git-Paper-655]
> 	at net.minecraft.server.v1_13_R2.MinecraftServer.run(MinecraftServer.java:787) ~[PS-1.13.2.jar:git-Paper-655]
> 	at java.lang.Thread.run(Unknown Source) [?:1.8.0_201]
> ```

You need remove `commands` section in `plugin.yml` to slove it. In `commands-api` 2.0, you don't need to add command to plugin description, it will be added automatically.

**Comment by TozyMC** [comment]
@gamerover98 You can get hot-patches from [Jitpack](https://jitpack.io/#TozyMC/commands-api/71674d895d) (temporary method)

**Comment by gamerover98** [comment]
> > After the updating from 1.1 to 2.0 of your API, my plugin doesn't work with any spigot version but, it throws a different error message into the stack trace.
> > ```
> > [05:23:57] [Server thread/INFO]: [NoBlackSky] Enabling NoBlackSky v2.1
> > [05:23:57] [Server thread/ERROR]: Error occurred while enabling NoBlackSky v2.1 (Is it up to date?)
> > java.lang.IllegalStateException: Command PluginCommand(name=NoBlackSky) is registered.
> > 	at com.google.common.base.Preconditions.checkState(Preconditions.java:518) ~[PS-1.13.2.jar:git-Paper-655]
> > 	at it.gamerover.nbs.libs.xyz.tozymc.spigot.api.command.CommandController.addCommand(CommandController.java:111) ~[?:?]
> > 	at it.gamerover.nbs.command.PluginCommand.<init>(PluginCommand.java:30) ~[?:?]
> > 	at it.gamerover.nbs.NoBlackSky.onEnable(NoBlackSky.java:108) ~[?:?]
> > 	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:265) ~[PS-1.13.2.jar:git-Paper-655]
> > 	at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:334) ~[PS-1.13.2.jar:git-Paper-655]
> > 	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:412) ~[PS-1.13.2.jar:git-Paper-655]
> > 	at org.bukkit.craftbukkit.v1_13_R2.CraftServer.enablePlugin(CraftServer.java:443) ~[PS-1.13.2.jar:git-Paper-655]
> > 	at org.bukkit.craftbukkit.v1_13_R2.CraftServer.enablePlugins(CraftServer.java:357) ~[PS-1.13.2.jar:git-Paper-655]
> > 	at net.minecraft.server.v1_13_R2.MinecraftServer.l(MinecraftServer.java:608) ~[PS-1.13.2.jar:git-Paper-655]
> > 	at net.minecraft.server.v1_13_R2.MinecraftServer.a(MinecraftServer.java:570) ~[PS-1.13.2.jar:git-Paper-655]
> > 	at net.minecraft.server.v1_13_R2.MinecraftServer.a(MinecraftServer.java:431) ~[PS-1.13.2.jar:git-Paper-655]
> > 	at net.minecraft.server.v1_13_R2.DedicatedServer.init(DedicatedServer.java:316) ~[PS-1.13.2.jar:git-Paper-655]
> > 	at net.minecraft.server.v1_13_R2.MinecraftServer.run(MinecraftServer.java:787) ~[PS-1.13.2.jar:git-Paper-655]
> > 	at java.lang.Thread.run(Unknown Source) [?:1.8.0_201]
> > ```
> 
> You need remove `commands` section in `plugin.yml` to slove it. In `commands-api` 2.0, you don't need to add command to plugin description, it will be added automatically.

Yes, it works but it doesn't work on 1.8.8 server:
`java.lang.NoSuchMethodError: com.google.common.base.Preconditions.checkState(ZLjava/lang/String;Ljava/lang/Object;)V`

I think that you must add manually guava into your maven project: https://mvnrepository.com/artifact/com.google.guava/guava/r05

**Comment by gamerover98** [comment]
I've found a solution:
1) The simplest but bad solution: add guava r05 into your maven dependencies and relocate it by maven-shade-plugin. The jar will weigh a lot (1 MB instead of 28 kb).
2) The best way: rewrite your own method or check with the simplest java 8 code if the argument of the method is null or invalid.

**Comment by TozyMC** [comment]
> I've found two different solutions:
> 
> 1. The simplest but bad solution: add guava r05 into your maven dependencies and relocate it by maven-shade-plugin. The jar will weigh a lot (1 MB instead of 28 kb).
> 2. The best way: rewrite your own method or check with the simplest java 8 code if the argument of the method is null or invalid.

I copied Preconditions class into my api. (71674d895d89fdfd2da292113507a102169e1c70). I will write own validation soon.


> @gamerover98 You can get hot-patches from [Jitpack](https://jitpack.io/#TozyMC/commands-api/71674d895d) (temporary method)

Jcenter repository is deprecated. I need to move the repository to another central. So I cannot publish to the current repository.

**Comment by gamerover98** [comment]
Thank you so much, it works!
Please, consider keeping opened this issue tracker until you'll publish the final version to the new repository ;)

**Comment by TozyMC** [comment]
> Thank you so much, it works!
> Please, consider keeping opened this issue tracker until you'll publish the final version to the new repository ;)

it's available on maven central
